#!/bin/bash

/usr/local/bin/mise trust /workspaces/devpod-base/mise.toml && /usr/local/bin/mise install

curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
chmod +x /usr/local/bin/kind

# sudo apt-get update && sudo apt-get upgrade -y && sudo-get apt install curl vim tmux -y
